<a href="https://colab.research.google.com/github/JunaedYounusKhan51/ENEL645/blob/main/Assignment-1/assignment01_python_numpy_programming_Group4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

**0. Cloning GitHub Repo of this Assignment**

In [ ]:
! git clone https://github.com/rmsouza01/ENEL645.git

Cloning into 'ENEL645'...
remote: Enumerating objects: 399, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 399 (delta 16), reused 31 (delta 8), pack-reused 355
Receiving objects: 100% (399/399), 136.13 MiB | 36.76 MiB/s, done.
Resolving deltas: 100% (175/175), done.


In [ ]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [ ]:
import numpy as np

# New Section

**2. Print the numpy version and the configuration**

In [ ]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


**3. Create a 1D array of zeros of size 10 of type float32**

In [ ]:
Z_array = np.zeros(10, dtype="float32")
print(Z_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [ ]:
Z = np.zeros((32,12))
# Include your solution below
print(Z.size * Z.itemsize)

3072


**5. Create a 1D array with values ranging from 10 to 58**

In [ ]:
A = np.arange(10,58+1)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [ ]:
a = np.arange(10)
# Include your solution below
print(a)
a = a[::-1]
print("After reversing the array:")
print(a)

[0 1 2 3 4 5 6 7 8 9]
After reversing the array:
[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [ ]:
a = np.arange(8+1) # 1D array with 8 elements

a = a.reshape(3,3) # Reshape. Now a is a 3x3 2D array
print('a.reshape(3,3) =')
print(a) 

a.reshape(3,3) =
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [ ]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [ ]:
Z = np.random.random((10,11))

# Include your solution below
max_along_columns = Z.max(axis=0)
print(max_along_columns) 

[0.98722436 0.97225009 0.74531511 0.91439536 0.84772922 0.92817808
 0.97837268 0.98357662 0.89850858 0.99950029 0.82355929]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [ ]:
x = np.ones((7,7))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [ ]:
Z = np.ones((5,5))
# Include your solution below
print("Given array:")
print(Z)
additional_row_up = 1
additional_row_down = 1 
additional_col_left = 1
additional_col_right = 1
additional_element_value = 0
Z = np.pad(Z,pad_width=((additional_row_up,additional_row_down),(additional_col_left,additional_col_right)),constant_values=((additional_element_value,additional_element_value),))
print("\nAfter padding %ds:" % additional_element_value)
print(Z)

Given array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

After padding 0s:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**



In [ ]:
Z = np.random.uniform(0,10,10)
# Include your solution below
print(Z)
Z_int = Z.astype(int)
print(Z_int)

[2.47329635 9.12425397 1.20589424 7.88056503 1.67024113 9.98875399
 3.68631549 5.92318563 1.19505381 5.60854612]
[2 9 1 7 1 9 3 5 1 5]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [ ]:
a = np.tile(np.arange(0,4+1), (5, 1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [ ]:
a = np.linspace(start=0, stop=1, num=10+1, endpoint=False)[1:]  #if endpoint=True, stop is the last sample. Otherwise, it is not included.
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [ ]:
a = np.random.rand(10)
print("A random array of size 10:")
print(a)
a = np.sort(a)
print("After sorting:")
print(a)

A random array of size 10:
[0.48912835 0.08883673 0.0357165  0.83231987 0.5068272  0.17722925
 0.46469952 0.59361882 0.21783543 0.78646044]
After sorting:
[0.0357165  0.08883673 0.17722925 0.21783543 0.46469952 0.48912835
 0.5068272  0.59361882 0.78646044 0.83231987]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
print("Given cartesial coordinates (X,Y):")
print(Z)

R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
polar_coord = np.dstack((R,T))
print("\nCorresponding polar coordinates (R,T):")
#print(R)
#print(T)
print(polar_coord)

Given cartesial coordinates (X,Y):
[[0.04065469 0.27384708]
 [0.62779549 0.74916374]
 [0.21373038 0.86859411]
 [0.04770156 0.47689964]
 [0.59256855 0.49058355]
 [0.2953612  0.9035284 ]
 [0.18976323 0.84405046]
 [0.84906324 0.38712194]
 [0.13993576 0.6650157 ]
 [0.65060379 0.05364408]]

Corresponding polar coordinates (R,T):
[[[0.27684838 1.42341513]
  [0.97743209 0.87331318]
  [0.89450344 1.32952486]
  [0.47927936 1.4711036 ]
  [0.76929169 0.69151918]
  [0.95057973 1.25484914]
  [0.86511921 1.34964892]
  [0.93315153 0.42778268]
  [0.67957921 1.36339736]
  [0.6528116  0.08226667]]]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [ ]:
a = np.random.rand(10)
print("A random array of size 10:")
print(a)
max_val_index = np.argmax(a)
a[max_val_index] = 0
print("After replacing the max value with 0:")
print(a)

A random array of size 10:
[0.28110983 0.31499535 0.89536564 0.07949908 0.89681734 0.44550333
 0.27096656 0.11808889 0.34430251 0.60022375]
After replacing the max value with 0:
[0.28110983 0.31499535 0.89536564 0.07949908 0.         0.44550333
 0.27096656 0.11808889 0.34430251 0.60022375]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
print("Given array:")
print(Z)
print("Reference value:")
print(z)
diff_array = abs(Z-z)
near_val_index = np.argmin(diff_array)
near_val = Z[near_val_index]
print("Nearest value from array:")
print(near_val)

Given array:
[0.46010649 0.14176796 0.3019472  0.00744439 0.69826086 0.12800131
 0.44024354 0.37904913 0.87460785 0.58094172]
Reference value:
0.5
Nearest value from array:
0.4601064862861157


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [ ]:
#Z = np.arange(5)[::-1]
Z = np.arange(6)[1:][::-1] #Changed a little, the original array was [4,3,2,1,0]
# Include your solution below
print("Original given array:")
print(Z)

value_to_insert = 0
numer_of_value_to_insert = 3
insert_index_array = sorted(list(np.arange(1,len(Z)))*numer_of_value_to_insert)
Z = np.insert(Z, insert_index_array, value_to_insert)

print("After inserting zeros:")
print(Z)

Original given array:
[5 4 3 2 1]
After inserting zeros:
[5 0 0 0 4 0 0 0 3 0 0 0 2 0 0 0 1]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [ ]:
A = np.ones((5,5,3))
#A = np.ones((3,5,5))
B = 2*np.ones((5,5))
# Include your solution below
print("A:")
print(A)
print("\nB:")
print(B)

M = (A.transpose() * B.transpose() ).transpose()
#M = A * B
print("\nAfter multiplication:")
print(M)

A:
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

B:
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

After multiplication:
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [ ]:
W = np.arange(30).reshape(6,5)
print("Original array:")
print(W)
print()
# Include your solution below
row1 = 0
row2 = 1
W[[row1, row2]] = W[[row2, row1]]
print("After swaping %d-th and %d-th rows:" % (row1+1,row2+1))
print(W)

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

After swaping 1-th and 2-th rows:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="https://github.com/rmsouza01/ENEL645/blob/master/Figures/bbox.png?raw=1" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

#img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
img = np.array(Image.open('/content/ENEL645/Figures/bbox.png').convert('L')) >0




print(bbox(img))



**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
'''def moving_average(x,N = 3):
    #define your function here
    i = 0
    m_avg_list = []
    while(i<len(x)):
      m_avg_list.append(np.average(x[i:i+N]))
      i = i + N
    return(m_avg_list)''' 


## Avoiding Explicit Python Loops
def moving_average(x,N = 3):
  #define your function here
  return np.add.reduceat(x, np.arange(0, len(x), N)) / N  #Reference (Documentation of reduceat): https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduceat.html

#a = np.arange(1,10)
a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here
#C = np.array([3,2,4])
A = np.repeat(np.arange(C.size), C) 
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below
print("Given array:")
print(Z)


'''
## 'bincount' cannot handle negative number 

most_frequent = np.bincount(Z).argmax()
print("Most frequent value:")
print(most_frequent)
'''

from collections import Counter
count = Counter(Z)
most_frequent = count.most_common(1)[0][0]
#print(count)
print("\nMost frequent value:")
print(most_frequent)

Given array:
[2 0 9 4 0 5 8 0 8 8 1 6 7 4 1 7 1 9 9 0 2 0 5 8 2 3 3 3 5 2 3 6 2 8 4 2 6
 3 0 2 8 5 6 5 1 8 7 3 7 3]

Most frequent value:
2


**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    a = np.sort(a)
    return a[-n:]

Z = np.arange(10000)
print("Given array:")
print(Z)
np.random.shuffle(Z)
n = 5
print("\n%d largest values:" % n)
print(nlargest(Z,n))    

Given array:
[   0    1    2 ... 9997 9998 9999]

5 largest values:
[9995 9996 9997 9998 9999]
