# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

**0. Cloning GitHub Repo of this Assignment**

In [ ]:
! git clone https://github.com/rmsouza01/ENEL645.git

Cloning into 'ENEL645'...
remote: Enumerating objects: 426, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 426 (delta 32), reused 50 (delta 16), pack-reused 355
Receiving objects: 100% (426/426), 138.00 MiB | 26.45 MiB/s, done.
Resolving deltas: 100% (191/191), done.


In [ ]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [ ]:
import numpy as np

**2. Print the numpy version and the configuration**

In [ ]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


**3. Create a 1D array of zeros of size 10 of type float32**

In [ ]:
Z = np.zeros(10, dtype="float32") #function to return an array of 0s
print("1D array of zeros of size 10 of type float32:")
print(Z)

1D array of zeros of size 10 of type float32:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [ ]:
Z = np.zeros((32,12))  #function to return an array of 0s
print("Memory size of the given array:")
print(Z.size * Z.itemsize) #Here: size = number of elements in Z, itemsize = size of each element

Memory size of the given array:
3072


**5. Create a 1D array with values ranging from 10 to 58**

In [ ]:
A = np.arange(10,58+1) #passing start value = 10 and end value = 58+1 (not inclusive)
print("1D array with values ranging from 10 to 58:")
print(A)

1D array with values ranging from 10 to 58:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [ ]:
a = np.arange(10) #1D array of 10 elements ranging from 0 to 9
# Include your solution below
print("Original array:")
print(a)
a = a[::-1] #reversing the array
print("After reversing the array:")
print(a)

Original array:
[0 1 2 3 4 5 6 7 8 9]
After reversing the array:
[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [ ]:
a = np.arange(8+1) # 1D array with 8 elements ranging from 0 to 8

a = a.reshape(3,3) # Reshape. Now a is a 3x3 2D array
print('3X3 matrix with values from 0 to 8:')
print(a) 

3X3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [ ]:
I = np.identity(3) #identity matrix of dimension 3X3
print("3X3 identity matrix:")
print(I)

3X3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [ ]:
Z = np.random.random((10,11))

# Include your solution below
print("Given array:")
print(Z)
max_along_columns = Z.max(axis=0) #maximum values of each column
print("\nMaximum values of each column:")
print(max_along_columns) 

Given array:
[[0.44786078 0.15534269 0.24651874 0.99115555 0.54234152 0.41757131
  0.14962484 0.38986986 0.4102397  0.76104854 0.8983896 ]
 [0.83232128 0.07990936 0.39157979 0.86575266 0.06858586 0.14580804
  0.47769241 0.74216866 0.42268304 0.49321692 0.10187964]
 [0.61401112 0.80142883 0.64789267 0.93426373 0.08194462 0.1586641
  0.84670098 0.416248   0.48273303 0.50383302 0.28886505]
 [0.90945008 0.71903677 0.81377587 0.35201422 0.94408444 0.86356222
  0.87812839 0.48848014 0.16226818 0.47891493 0.71454783]
 [0.80892631 0.50537221 0.93261191 0.4822075  0.49434001 0.37062643
  0.38197229 0.62606889 0.2400379  0.05412323 0.52142084]
 [0.64931821 0.85128614 0.23951669 0.65350555 0.41541208 0.94297836
  0.6252844  0.43122237 0.90242211 0.22513297 0.28909933]
 [0.67697317 0.4874407  0.11393142 0.37239386 0.04024381 0.06314794
  0.65924297 0.54553969 0.54592928 0.85935348 0.26941952]
 [0.1178882  0.65094774 0.8283163  0.05105667 0.14241712 0.66719866
  0.03019193 0.86502041 0.12268196 0.8

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [ ]:
Z = np.ones((7,7)) #7X7 array of 1s
Z[1:-1,1:-1] = 0 #putting 0 on non-border elements 
print("7X7 array with 1s on the borders and 0s everywhere else:")
print(Z)

7X7 array with 1s on the borders and 0s everywhere else:
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [ ]:
Z = np.ones((5,5))
# Include your solution below
print("Given array:")
print(Z)

#defining pad width (for example, we considered pad_width of 1)
additional_row_up = 1 #number of padded row above
additional_row_down = 1 #number of padded row below
additional_col_left = 1 #number of padded column right
additional_col_right = 1 #number of padded column left

#defining the value to pad with
additional_element_value = 0 # here we are padding with 0

Z = np.pad(Z,pad_width=((additional_row_up,additional_row_down),(additional_col_left,additional_col_right)),constant_values=((additional_element_value,additional_element_value),))
print("\nAfter padding %ds:" % additional_element_value)
print(Z)

Given array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

After padding 0s:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**



In [ ]:
Z = np.random.uniform(0,10,10)
# Include your solution below
print("Given array:")
print(Z)
Z_int = Z.astype(int)
print("\nIntegar parts extracted from the array:")
print(Z_int)

Given array:
[8.48254099 8.45903614 9.27454286 7.32755057 0.1918985  9.94861524
 5.56383468 9.27377012 6.96176696 2.14495632]

Integar parts extracted from the array:
[8 8 9 7 0 9 5 9 6 2]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [ ]:
dimension = 5 #for 5X5 array
a = np.arange(0,dimension) # 1D array with elements 0 to 4
Z = np.tile(a, (dimension, 1)) # preparing 2D (5X5) array with row similar to 1D (1X5) array
print("%d X %d matrix with rows ranging from 0 to %d:" % (dimension, dimension, dimension-1)) 
print(Z)

5 X 5 matrix with rows ranging from 0 to 4:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [ ]:
a = np.linspace(start=0, stop=1, num=10+1, endpoint=False)[1:]  #if endpoint=True, stop is the last sample. Otherwise, it is not included.
print("Vector of size 10 with values in (0,1) range:")
print(a)

Vector of size 10 with values in (0,1) range:
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [ ]:
a = np.random.rand(10) #random array of size 10
print("A random array of size 10:")
print(a)
a = np.sort(a) #sorting the array
print("After sorting:")
print(a)

A random array of size 10:
[0.63262393 0.9565052  0.14885442 0.62789399 0.34279225 0.28904862
 0.32507985 0.1368909  0.89658089 0.6881541 ]
After sorting:
[0.1368909  0.14885442 0.28904862 0.32507985 0.34279225 0.62789399
 0.63262393 0.6881541  0.89658089 0.9565052 ]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
print("Given cartesial coordinates (X,Y):")
print(Z)

# converting cartesian to polar coordinates
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
polar_coord = np.dstack((R,T))

# printing polar points
print("\nCorresponding polar coordinates (R,T):")
#print(R)
#print(T)
print(polar_coord)

Given cartesial coordinates (X,Y):
[[0.53193663 0.47303603]
 [0.81569446 0.44071251]
 [0.95677122 0.6252309 ]
 [0.7405289  0.77102254]
 [0.47138165 0.66302592]
 [0.53609786 0.40243973]
 [0.32315268 0.50682346]
 [0.07068711 0.52745991]
 [0.98892946 0.2803471 ]
 [0.20232655 0.27483297]]

Corresponding polar coordinates (R,T):
[[[0.71184244 0.72685597]
  [0.92713806 0.49535867]
  [1.14294568 0.57881776]
  [1.06904575 0.80556916]
  [0.81351338 0.95275573]
  [0.67034219 0.6439383 ]
  [0.60108042 1.00318473]
  [0.53217537 1.4375759 ]
  [1.02789882 0.27623781]
  [0.34127584 0.93619881]]]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [ ]:
a = np.random.rand(10) #random array of size 10
print("A random array of size 10:")
print(a)

max_val_index = np.argmax(a) #index of the max value
a[max_val_index] = 0 # replacing the max value by 0 (putting 0 in max value index)

print("\nAfter replacing the max value with 0:")
print(a)

A random array of size 10:
[0.11472675 0.16877425 0.38872526 0.43346232 0.22041387 0.98043591
 0.46855936 0.51478269 0.23680676 0.72079732]

After replacing the max value with 0:
[0.11472675 0.16877425 0.38872526 0.43346232 0.22041387 0.
 0.46855936 0.51478269 0.23680676 0.72079732]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5

# Include your solution below
print("Given array:")
print(Z)

print("\nReference value:")
print(z)

diff_array = abs(Z-z) # taking difference from the reference value
near_val_index = np.argmin(diff_array) #index of nearest value
near_val = Z[near_val_index] # nearest value

print("\nNearest value from array:")
print(near_val)

Given array:
[0.19745592 0.061205   0.75316364 0.96453296 0.84012535 0.15779222
 0.78294566 0.52470442 0.33868334 0.05411812]

Reference value:
0.5

Nearest value from array:
0.524704422524014


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [ ]:
#Z = np.arange(5)[::-1]
Z = np.arange(6)[1:][::-1] #Changed a little, the original array was [4,3,2,1,0]
# Include your solution below
print("Original given array:")
print(Z)

value_to_insert = 0
numer_of_value_to_insert = 3
insert_index_array = (list(np.arange(1,len(Z)))*numer_of_value_to_insert)
#print(insert_index_array)
Z = np.insert(Z, insert_index_array, value_to_insert)

print("\nAfter inserting zeros:")
print(Z)

Original given array:
[5 4 3 2 1]

After inserting zeros:
[5 0 0 0 4 0 0 0 3 0 0 0 2 0 0 0 1]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [ ]:
A = np.ones((5,5,3))
#A = np.ones((3,5,5))
B = 2*np.ones((5,5))
# Include your solution below
print("A:")
print(A)
print("\nB:")
print(B)

M = (A.transpose() * B.transpose() ).transpose() #multiplying A and B
#M = A * B
print("\nAfter multiplication:")
print(M)

A:
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

B:
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

After multiplication:
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [ ]:
W = np.arange(30).reshape(6,5)
print("Original array:")
print(W)
print()
# Include your solution below

# Defining the rows to be swapped
row1 = 0 # first row
row2 = 1 # second row
W[[row1, row2]] = W[[row2, row1]] # swapping

print("After swaping %d-th and %d-th rows:" % (row1+1,row2+1))
print(W)

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

After swaping 1-th and 2-th rows:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="https://github.com/rmsouza01/ENEL645/blob/master/Figures/bbox.png?raw=1" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    img_non_zero = np.where(img!=0) # non-zero element
    #print(img_non_zero)
    r1 = np.min(img_non_zero[0])
    r2 = np.max(img_non_zero[0])
    c1 =  np.min(img_non_zero[1])
    c2 =  np.max(img_non_zero[1])
    return (r1,c1),(r2,c2)


from PIL import Image

#img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
img = np.array(Image.open('/content/ENEL645/Figures/bbox.png').convert('L')) >0

print("Coordinates of the minimum bounding-box enclosing all non-zeros:")
print(bbox(img))


## Self-made array for testing purpose
#x = np.zeros((7,7))
#x[1:-1,1:-1] = 1
#x[:,1] = 0
#x[:,5] = 0
#print(x)
#print(bbox(x))

Coordinates of the minimum bounding-box enclosing all non-zeros:
((0, 0), (219, 193))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
'''def moving_average(x,N = 3):
    #define your function here
    i = 0
    m_avg_list = []
    while(i<len(x)):
      m_avg_list.append(np.average(x[i:i+N]))
      i = i + N
    return(m_avg_list)''' 

import numpy as np

## Avoiding Explicit Python Loops
def moving_average(x,N = 3):
  return np.add.reduceat(x, np.arange(0, len(x), N)) / N  #Reference (Documentation of reduceat): https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduceat.html

#a = np.arange(1,10)
a = np.arange(30)
print("Given array:")
print(a)

N = 3
print("\nMoving avg over a sliding window of len %d:" % N)
print(moving_average(a,N))

Given array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

Moving avg over a sliding window of len 3:
[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print("Given array C:")
print(C)
# Include yoru solution here
#C = np.array([3,2,4])
print("\nOutput A:")
A = np.repeat(np.arange(C.size), C) 
print(A)

Given array C:
[0 2 1 1 2 0 1]

Output A:
[1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below
print("Given array:")
print(Z)


'''
## 'bincount' cannot handle negative number 

most_frequent = np.bincount(Z).argmax()
print("Most frequent value:")
print(most_frequent)
'''

from collections import Counter
count = Counter(Z)
most_frequent = count.most_common(1)[0][0]
#print(count)
print("\nMost frequent value:")
print(most_frequent)

Given array:
[8 6 0 9 4 3 9 4 2 0 1 0 2 5 1 5 2 6 6 7 9 0 8 4 6 9 5 4 8 7 8 4 6 9 0 1 4
 2 9 8 5 0 4 4 3 8 2 4 0 9]

Most frequent value:
4


**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    a = np.sort(a) #sorting the array in increasing order
    return a[-n:] #taking last n (largest) numbers of the sorted array

Z = np.arange(10000)
print("Given array:")
print(Z)
np.random.shuffle(Z)
n = 5
print("\n%d largest values:" % n)
print(nlargest(Z,n))    

Given array:
[   0    1    2 ... 9997 9998 9999]

5 largest values:
[9995 9996 9997 9998 9999]
